baseURL: "https://louisedemoor.github.io" 
title: Louise Demoor
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /papers/
          weight: 1 
        - name: Resume
          url: cv/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
        - name: News
          url: news/
          weight: 4 

params:
    description: "I am a first year Ph.D. student in Economics at CREST."
    author: Louise Demoor
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    #MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Louise Demoor
          subtitle: "Welcome! I am a PhD student in economics at CREST, working under the supervision of Professor [<u>Julien Combe</u>](https://sites.google.com/site/combeju/home).
           <br>  <br> My research area is [<u>market design</u>](https://en.wikipedia.org/wiki/Market_design). I am particularly interested in improving allocation systems by relaxing 
           the traditional assumption that agents participate in these mechanisms in a fixed and exogenous way, and by identifying the factors that influence agents’ decisions to participate. 
           Currently, I am primarily working on the topic of kidney exchange, but I also aim to explore other areas such as student assignment in schools. "
          imageUrl: "picture.jpeg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Research
              url: papers/
            - name:  Resume
              url: cv/
            - name : Teaching
              url: courses/
            - name: News
              url: news/
           # - name: Archive
            #  url: archive/

    socialIcons:
        - name: CV
          url: Academic_Resume.pdf
        - name: Email
          url: mailto:louise.demoor@ensae.fr
        - name: orcid
          url: https://orcid.org/0009-0008-3305-3375
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/louisedemoor


    assets:
        #disableHLJS: true
        disableScrollBarStyle: true
        #favicon: "/favicon.ico"
        #favicon16x16: "/favicon-16x16.png"
        #favicon32x32: "/favicon-32x32.png"
        #apple_touch_icon: "/apple-touch-icon.png"
        #mask_icon: "/favicon.png"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Louise Demoor"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2